models:
  place:
    image:
      width: 400
      height: 400
  user:
    image:
      width: 400
      height: 400
    password:
      min_len: 6
    name:
      max_len: 50
    email:
      max_len: 100
sessions:
  checked_remember: 1
  uncheck_remember: 0
show_limit:
  show_15: 15
  show_9: 9
  show_6: 6
  show_5: 5
truncate_place_descriptions: 100
